[2024-03-28T02:46:33.855+0000] {processor.py:153} INFO - Started process (PID=413) to work on /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py
[2024-03-28T02:46:33.868+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py for tasks to queue
[2024-03-28T02:46:33.871+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:46:33.871+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py
[2024-03-28T02:46:33.914+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:46:33.906+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py", line 5, in <module>
    from airflow.providers.amazon.aws.sensors.s3_key import S3KeySensor
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.sensors.s3_key'
[2024-03-28T02:46:33.915+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py
[2024-03-28T02:46:34.068+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py took 0.230 seconds
[2024-03-28T02:47:38.335+0000] {processor.py:153} INFO - Started process (PID=663) to work on /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py
[2024-03-28T02:47:38.340+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py for tasks to queue
[2024-03-28T02:47:38.343+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:47:38.343+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py
[2024-03-28T02:47:38.392+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:47:38.388+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py", line 5, in <module>
    from airflow.providers.amazon.aws.sensors.s3_key import S3KeySensor
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.sensors.s3_key'
[2024-03-28T02:47:38.394+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py
[2024-03-28T02:47:38.483+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py took 0.163 seconds
[2024-03-28T02:48:28.200+0000] {processor.py:153} INFO - Started process (PID=891) to work on /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py
[2024-03-28T02:48:28.209+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py for tasks to queue
[2024-03-28T02:48:28.211+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:48:28.211+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py
[2024-03-28T02:48:28.247+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:48:28.242+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py", line 5, in <module>
    from airflow.providers.amazon.aws.sensors.s3_key import S3KeySensor
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.sensors.s3_key'
[2024-03-28T02:48:28.249+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py
[2024-03-28T02:48:28.298+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py took 0.110 seconds
[2024-03-28T02:48:58.626+0000] {processor.py:153} INFO - Started process (PID=1089) to work on /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py
[2024-03-28T02:48:58.631+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py for tasks to queue
[2024-03-28T02:48:58.637+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:48:58.636+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py
[2024-03-28T02:48:58.660+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:48:58.656+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py", line 5, in <module>
    from airflow.providers.amazon.aws.sensors.s3_key import S3KeySensor
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.sensors.s3_key'
[2024-03-28T02:48:58.665+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py
[2024-03-28T02:48:58.754+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py took 0.137 seconds
[2024-03-28T02:49:31.339+0000] {processor.py:153} INFO - Started process (PID=1302) to work on /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py
[2024-03-28T02:49:31.340+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py for tasks to queue
[2024-03-28T02:49:31.342+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:49:31.342+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py
[2024-03-28T02:49:31.362+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:49:31.359+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py", line 5, in <module>
    from airflow.providers.amazon.aws.sensors.s3_key import S3KeySensor
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.sensors.s3_key'
[2024-03-28T02:49:31.364+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py
[2024-03-28T02:49:31.401+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py took 0.069 seconds
[2024-03-28T02:50:03.290+0000] {processor.py:153} INFO - Started process (PID=1511) to work on /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py
[2024-03-28T02:50:03.308+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py for tasks to queue
[2024-03-28T02:50:03.314+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:50:03.314+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py
[2024-03-28T02:50:03.341+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:50:03.338+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py", line 5, in <module>
    from airflow.providers.amazon.aws.sensors.s3_key import S3KeySensor
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.sensors.s3_key'
[2024-03-28T02:50:03.343+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py
[2024-03-28T02:50:03.406+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py took 0.124 seconds
[2024-03-28T02:50:50.270+0000] {processor.py:153} INFO - Started process (PID=1767) to work on /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py
[2024-03-28T02:50:50.272+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py for tasks to queue
[2024-03-28T02:50:50.276+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:50:50.275+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py
[2024-03-28T02:50:50.305+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:50:50.301+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py", line 5, in <module>
    from airflow.providers.amazon.aws.sensors.s3_key import S3KeySensor
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.sensors.s3_key'
[2024-03-28T02:50:50.307+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py
[2024-03-28T02:50:50.362+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py took 0.100 seconds
[2024-03-28T02:51:21.167+0000] {processor.py:153} INFO - Started process (PID=1973) to work on /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py
[2024-03-28T02:51:21.169+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py for tasks to queue
[2024-03-28T02:51:21.170+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:51:21.170+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py
[2024-03-28T02:51:21.188+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:51:21.185+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py", line 5, in <module>
    from airflow.providers.amazon.aws.sensors.s3_key import S3KeySensor
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.sensors.s3_key'
[2024-03-28T02:51:21.189+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py
[2024-03-28T02:51:21.228+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py took 0.069 seconds
[2024-03-28T02:51:52.890+0000] {processor.py:153} INFO - Started process (PID=2179) to work on /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py
[2024-03-28T02:51:52.894+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py for tasks to queue
[2024-03-28T02:51:52.900+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:51:52.899+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py
[2024-03-28T02:51:52.939+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:51:52.936+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py", line 5, in <module>
    from airflow.providers.amazon.aws.sensors.s3_key import S3KeySensor
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.sensors.s3_key'
[2024-03-28T02:51:52.942+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py
[2024-03-28T02:51:53.014+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py took 0.135 seconds
[2024-03-28T02:52:24.171+0000] {processor.py:153} INFO - Started process (PID=2390) to work on /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py
[2024-03-28T02:52:24.181+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py for tasks to queue
[2024-03-28T02:52:24.194+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:52:24.193+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py
[2024-03-28T02:52:24.255+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:52:24.239+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py", line 5, in <module>
    from airflow.providers.amazon.aws.sensors.s3_key import S3KeySensor
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.sensors.s3_key'
[2024-03-28T02:52:24.267+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py
[2024-03-28T02:52:24.422+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py took 0.268 seconds
[2024-03-28T02:52:56.766+0000] {processor.py:153} INFO - Started process (PID=2595) to work on /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py
[2024-03-28T02:52:56.768+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py for tasks to queue
[2024-03-28T02:52:56.769+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:52:56.769+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py
[2024-03-28T02:52:56.787+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:52:56.785+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py", line 5, in <module>
    from airflow.providers.amazon.aws.sensors.s3_key import S3KeySensor
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.sensors.s3_key'
[2024-03-28T02:52:56.789+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py
[2024-03-28T02:52:56.824+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py took 0.066 seconds
[2024-03-28T02:53:28.107+0000] {processor.py:153} INFO - Started process (PID=2790) to work on /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py
[2024-03-28T02:53:28.108+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py for tasks to queue
[2024-03-28T02:53:28.109+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:53:28.109+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py
[2024-03-28T02:53:28.127+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:53:28.125+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py", line 5, in <module>
    from airflow.providers.amazon.aws.sensors.s3_key import S3KeySensor
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.sensors.s3_key'
[2024-03-28T02:53:28.129+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py
[2024-03-28T02:53:28.164+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py took 0.063 seconds
[2024-03-28T02:53:59.742+0000] {processor.py:153} INFO - Started process (PID=3010) to work on /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py
[2024-03-28T02:53:59.744+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py for tasks to queue
[2024-03-28T02:53:59.745+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:53:59.745+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py
[2024-03-28T02:53:59.766+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:53:59.760+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py", line 5, in <module>
    from airflow.providers.amazon.aws.sensors.s3_key import S3KeySensor
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.sensors.s3_key'
[2024-03-28T02:53:59.768+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py
[2024-03-28T02:53:59.800+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py took 0.063 seconds
[2024-03-28T02:54:31.789+0000] {processor.py:153} INFO - Started process (PID=3216) to work on /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py
[2024-03-28T02:54:31.791+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py for tasks to queue
[2024-03-28T02:54:31.792+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:54:31.792+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py
[2024-03-28T02:54:31.809+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:54:31.807+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py", line 5, in <module>
    from airflow.providers.amazon.aws.sensors.s3_key import S3KeySensor
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.sensors.s3_key'
[2024-03-28T02:54:31.810+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py
[2024-03-28T02:54:31.839+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py took 0.054 seconds
[2024-03-28T02:55:02.943+0000] {processor.py:153} INFO - Started process (PID=3429) to work on /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py
[2024-03-28T02:55:02.945+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py for tasks to queue
[2024-03-28T02:55:02.949+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:55:02.948+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py
[2024-03-28T02:55:02.965+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:55:02.961+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py", line 5, in <module>
    from airflow.providers.amazon.aws.sensors.s3_key import S3KeySensor
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.sensors.s3_key'
[2024-03-28T02:55:02.967+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py
[2024-03-28T02:55:03.000+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py took 0.061 seconds
[2024-03-28T02:55:34.517+0000] {processor.py:153} INFO - Started process (PID=3639) to work on /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py
[2024-03-28T02:55:34.519+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py for tasks to queue
[2024-03-28T02:55:34.520+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:55:34.520+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py
[2024-03-28T02:55:34.533+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:55:34.531+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py", line 5, in <module>
    from airflow.providers.amazon.aws.sensors.s3_key import S3KeySensor
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.sensors.s3_key'
[2024-03-28T02:55:34.534+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py
[2024-03-28T02:55:34.560+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py took 0.050 seconds
[2024-03-28T02:56:05.772+0000] {processor.py:153} INFO - Started process (PID=3850) to work on /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py
[2024-03-28T02:56:05.773+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py for tasks to queue
[2024-03-28T02:56:05.775+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:56:05.774+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py
[2024-03-28T02:56:05.790+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:56:05.788+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py", line 5, in <module>
    from airflow.providers.amazon.aws.sensors.s3_key import S3KeySensor
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.sensors.s3_key'
[2024-03-28T02:56:05.791+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py
[2024-03-28T02:56:05.821+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py took 0.054 seconds
[2024-03-28T02:56:36.886+0000] {processor.py:153} INFO - Started process (PID=4061) to work on /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py
[2024-03-28T02:56:36.888+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py for tasks to queue
[2024-03-28T02:56:36.889+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:56:36.889+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py
[2024-03-28T02:56:36.905+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:56:36.903+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py", line 5, in <module>
    from airflow.providers.amazon.aws.sensors.s3_key import S3KeySensor
ModuleNotFoundError: No module named 'airflow.providers.amazon.aws.sensors.s3_key'
[2024-03-28T02:56:36.907+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py
[2024-03-28T02:56:36.936+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dw_poc/ad_event_logs_kafka_poc.py took 0.054 seconds
