[2024-03-28T02:45:36.323+0000] {processor.py:153} INFO - Started process (PID=228) to work on /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py
[2024-03-28T02:45:36.326+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py for tasks to queue
[2024-03-28T02:45:36.328+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:45:36.327+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py
[2024-03-28T02:45:38.497+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:45:38.490+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/houzz_pro/dags/dag_update_s3.py", line 34, in <module>
    KEY = Variable.get("aws_access_key_id_val")
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable aws_access_key_id_val does not exist'
[2024-03-28T02:45:38.498+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py
[2024-03-28T02:45:38.545+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py took 2.231 seconds
[2024-03-28T02:46:45.664+0000] {processor.py:153} INFO - Started process (PID=466) to work on /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py
[2024-03-28T02:46:45.666+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py for tasks to queue
[2024-03-28T02:46:45.668+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:46:45.668+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py
[2024-03-28T02:46:52.973+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:46:52.964+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/houzz_pro/dags/dag_update_s3.py", line 34, in <module>
    KEY = Variable.get("aws_access_key_id_val")
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable aws_access_key_id_val does not exist'
[2024-03-28T02:46:52.980+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py
[2024-03-28T02:46:53.032+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py took 7.383 seconds
[2024-03-28T02:47:41.436+0000] {processor.py:153} INFO - Started process (PID=685) to work on /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py
[2024-03-28T02:47:41.439+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py for tasks to queue
[2024-03-28T02:47:41.441+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:47:41.441+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py
[2024-03-28T02:47:44.038+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:47:44.031+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/houzz_pro/dags/dag_update_s3.py", line 34, in <module>
    KEY = Variable.get("aws_access_key_id_val")
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable aws_access_key_id_val does not exist'
[2024-03-28T02:47:44.051+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py
[2024-03-28T02:47:44.082+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py took 2.658 seconds
[2024-03-28T02:48:30.331+0000] {processor.py:153} INFO - Started process (PID=903) to work on /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py
[2024-03-28T02:48:30.333+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py for tasks to queue
[2024-03-28T02:48:30.337+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:48:30.336+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py
[2024-03-28T02:48:33.971+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:48:33.959+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/houzz_pro/dags/dag_update_s3.py", line 34, in <module>
    KEY = Variable.get("aws_access_key_id_val")
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable aws_access_key_id_val does not exist'
[2024-03-28T02:48:33.973+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py
[2024-03-28T02:48:33.998+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py took 3.701 seconds
[2024-03-28T02:49:04.154+0000] {processor.py:153} INFO - Started process (PID=1108) to work on /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py
[2024-03-28T02:49:04.156+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py for tasks to queue
[2024-03-28T02:49:04.158+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:49:04.158+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py
[2024-03-28T02:49:05.038+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:49:05.036+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/houzz_pro/dags/dag_update_s3.py", line 34, in <module>
    KEY = Variable.get("aws_access_key_id_val")
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable aws_access_key_id_val does not exist'
[2024-03-28T02:49:05.039+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py
[2024-03-28T02:49:05.052+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py took 0.906 seconds
[2024-03-28T02:49:35.490+0000] {processor.py:153} INFO - Started process (PID=1319) to work on /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py
[2024-03-28T02:49:35.492+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py for tasks to queue
[2024-03-28T02:49:35.493+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:49:35.493+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py
[2024-03-28T02:49:37.030+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:49:37.023+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/houzz_pro/dags/dag_update_s3.py", line 34, in <module>
    KEY = Variable.get("aws_access_key_id_val")
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable aws_access_key_id_val does not exist'
[2024-03-28T02:49:37.032+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py
[2024-03-28T02:49:37.049+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py took 1.566 seconds
[2024-03-28T02:50:07.598+0000] {processor.py:153} INFO - Started process (PID=1530) to work on /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py
[2024-03-28T02:50:07.600+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py for tasks to queue
[2024-03-28T02:50:07.603+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:50:07.602+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py
[2024-03-28T02:50:08.685+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:50:08.676+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/houzz_pro/dags/dag_update_s3.py", line 34, in <module>
    KEY = Variable.get("aws_access_key_id_val")
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable aws_access_key_id_val does not exist'
[2024-03-28T02:50:08.696+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py
[2024-03-28T02:50:08.713+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py took 1.122 seconds
[2024-03-28T02:50:45.406+0000] {processor.py:153} INFO - Started process (PID=1723) to work on /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py
[2024-03-28T02:50:45.414+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py for tasks to queue
[2024-03-28T02:50:45.424+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:50:45.424+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py
[2024-03-28T02:50:46.863+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:50:46.857+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/houzz_pro/dags/dag_update_s3.py", line 34, in <module>
    KEY = Variable.get("aws_access_key_id_val")
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable aws_access_key_id_val does not exist'
[2024-03-28T02:50:46.878+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py
[2024-03-28T02:50:46.921+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py took 1.532 seconds
[2024-03-28T02:51:17.230+0000] {processor.py:153} INFO - Started process (PID=1934) to work on /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py
[2024-03-28T02:51:17.232+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py for tasks to queue
[2024-03-28T02:51:17.234+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:51:17.233+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py
[2024-03-28T02:51:18.239+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:51:18.226+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/houzz_pro/dags/dag_update_s3.py", line 34, in <module>
    KEY = Variable.get("aws_access_key_id_val")
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable aws_access_key_id_val does not exist'
[2024-03-28T02:51:18.247+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py
[2024-03-28T02:51:18.265+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py took 1.094 seconds
[2024-03-28T02:51:48.750+0000] {processor.py:153} INFO - Started process (PID=2145) to work on /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py
[2024-03-28T02:51:48.756+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py for tasks to queue
[2024-03-28T02:51:48.760+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:51:48.759+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py
[2024-03-28T02:51:50.597+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:51:50.592+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/houzz_pro/dags/dag_update_s3.py", line 34, in <module>
    KEY = Variable.get("aws_access_key_id_val")
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable aws_access_key_id_val does not exist'
[2024-03-28T02:51:50.599+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py
[2024-03-28T02:51:50.635+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py took 1.904 seconds
[2024-03-28T02:52:21.644+0000] {processor.py:153} INFO - Started process (PID=2349) to work on /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py
[2024-03-28T02:52:21.646+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py for tasks to queue
[2024-03-28T02:52:21.649+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:52:21.649+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py
[2024-03-28T02:52:22.738+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:52:22.735+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/houzz_pro/dags/dag_update_s3.py", line 34, in <module>
    KEY = Variable.get("aws_access_key_id_val")
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable aws_access_key_id_val does not exist'
[2024-03-28T02:52:22.739+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py
[2024-03-28T02:52:22.755+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py took 1.117 seconds
[2024-03-28T02:52:54.722+0000] {processor.py:153} INFO - Started process (PID=2572) to work on /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py
[2024-03-28T02:52:54.724+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py for tasks to queue
[2024-03-28T02:52:54.726+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:52:54.725+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py
[2024-03-28T02:52:56.096+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:52:56.092+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/houzz_pro/dags/dag_update_s3.py", line 34, in <module>
    KEY = Variable.get("aws_access_key_id_val")
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable aws_access_key_id_val does not exist'
[2024-03-28T02:52:56.097+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py
[2024-03-28T02:52:56.107+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py took 1.397 seconds
[2024-03-28T02:53:26.480+0000] {processor.py:153} INFO - Started process (PID=2766) to work on /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py
[2024-03-28T02:53:26.483+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py for tasks to queue
[2024-03-28T02:53:26.484+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:53:26.484+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py
[2024-03-28T02:53:27.612+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:53:27.609+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/houzz_pro/dags/dag_update_s3.py", line 34, in <module>
    KEY = Variable.get("aws_access_key_id_val")
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable aws_access_key_id_val does not exist'
[2024-03-28T02:53:27.615+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py
[2024-03-28T02:53:27.628+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py took 1.156 seconds
[2024-03-28T02:53:58.287+0000] {processor.py:153} INFO - Started process (PID=2995) to work on /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py
[2024-03-28T02:53:58.288+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py for tasks to queue
[2024-03-28T02:53:58.289+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:53:58.289+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py
[2024-03-28T02:53:59.665+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:53:59.658+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/houzz_pro/dags/dag_update_s3.py", line 34, in <module>
    KEY = Variable.get("aws_access_key_id_val")
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable aws_access_key_id_val does not exist'
[2024-03-28T02:53:59.667+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py
[2024-03-28T02:53:59.682+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py took 1.402 seconds
[2024-03-28T02:54:29.949+0000] {processor.py:153} INFO - Started process (PID=3206) to work on /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py
[2024-03-28T02:54:29.951+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py for tasks to queue
[2024-03-28T02:54:29.953+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:54:29.953+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py
[2024-03-28T02:54:31.757+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:54:31.754+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/houzz_pro/dags/dag_update_s3.py", line 34, in <module>
    KEY = Variable.get("aws_access_key_id_val")
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable aws_access_key_id_val does not exist'
[2024-03-28T02:54:31.758+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py
[2024-03-28T02:54:31.772+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py took 1.830 seconds
[2024-03-28T02:55:02.062+0000] {processor.py:153} INFO - Started process (PID=3417) to work on /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py
[2024-03-28T02:55:02.064+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py for tasks to queue
[2024-03-28T02:55:02.066+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:55:02.065+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py
[2024-03-28T02:55:02.894+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:55:02.891+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/houzz_pro/dags/dag_update_s3.py", line 34, in <module>
    KEY = Variable.get("aws_access_key_id_val")
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable aws_access_key_id_val does not exist'
[2024-03-28T02:55:02.896+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py
[2024-03-28T02:55:02.909+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py took 0.852 seconds
[2024-03-28T02:55:33.573+0000] {processor.py:153} INFO - Started process (PID=3627) to work on /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py
[2024-03-28T02:55:33.575+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py for tasks to queue
[2024-03-28T02:55:33.576+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:55:33.576+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py
[2024-03-28T02:55:34.471+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:55:34.468+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/houzz_pro/dags/dag_update_s3.py", line 34, in <module>
    KEY = Variable.get("aws_access_key_id_val")
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable aws_access_key_id_val does not exist'
[2024-03-28T02:55:34.472+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py
[2024-03-28T02:55:34.484+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py took 0.919 seconds
[2024-03-28T02:56:04.908+0000] {processor.py:153} INFO - Started process (PID=3838) to work on /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py
[2024-03-28T02:56:04.910+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py for tasks to queue
[2024-03-28T02:56:04.911+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:56:04.911+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py
[2024-03-28T02:56:05.721+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:56:05.718+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/houzz_pro/dags/dag_update_s3.py", line 34, in <module>
    KEY = Variable.get("aws_access_key_id_val")
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable aws_access_key_id_val does not exist'
[2024-03-28T02:56:05.722+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py
[2024-03-28T02:56:05.735+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py took 0.832 seconds
[2024-03-28T02:56:36.000+0000] {processor.py:153} INFO - Started process (PID=4049) to work on /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py
[2024-03-28T02:56:36.002+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py for tasks to queue
[2024-03-28T02:56:36.003+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:56:36.003+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py
[2024-03-28T02:56:36.847+0000] {logging_mixin.py:137} INFO - [2024-03-28T02:56:36.844+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/houzz_pro/dags/dag_update_s3.py", line 34, in <module>
    KEY = Variable.get("aws_access_key_id_val")
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/variable.py", line 141, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable aws_access_key_id_val does not exist'
[2024-03-28T02:56:36.848+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py
[2024-03-28T02:56:36.860+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/houzz_pro/dags/dag_update_s3.py took 0.867 seconds
